### ISSUE TITLE
If the number of containers is greater than the number of partitions created by the partitioner, we get the following error

### ISSUE THREAD

**Issue by concurrent-ai** [concurrent-ai/concurrent#27]
Suppose we have a partitioner that creates three partitions out of the data, and suppose we set the 'Number of Containers' to 4, then we get the following exception - KeyError: 'FileName' in the last container that does not get any partitioned data.

-----
honeypot: Entered
Input spec config path: /root/.concurrent-data/inputdataspec-4-16643340647140000000015
Input specs for input_name  cowrie :  [{'name': 'cowrie', 'type': 'infinsnap', 'bucketname': 'juniper-testbucket', 'prefix': 'test', 'time_spec': 'tm20220928030049', 'parallelization_schedule': ['default', 4, 3], 'partition_keygen': "lambda row:row['FileName'].split('/')[-1].split('-')[0]"}]
Processing input spec:  {'name': 'cowrie', 'type': 'infinsnap', 'bucketname': 'juniper-testbucket', 'prefix': 'test', 'time_spec': 'tm20220928030049', 'parallelization_schedule': ['default', 4, 3], 'partition_keygen': "lambda row:row['FileName'].split('/')[-1].split('-')[0]"}
infinstor: Activating time_spec=tm20220928030049
get_customerinfo: usePresignedUrlForInfinSnap=true
get_customerinfo: usePresignedUrlForMLflow=true
INFO: _list_one_dir:  juniper-testbucket test
infin_boto3: intercept activated for buckets=['juniper-testbucket']
INFO: _list_one_dir:  juniper-testbucket test/
Keygen function for partitioning: lambda row:row['FileName'].split('/')[-1].split('-')[0]
Column Names:
[]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'FileName'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "honeypot.py", line 19, in <module>
    lp = concurrent_core.get_local_paths(df)
  File "/usr/local/lib/python3.7/site-packages/concurrent_plugin/concurrent_core.py", line 263, in get_local_paths
    return df['FileName'].tolist()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'FileName'

**Comment by jnp** [comment]
I see, it should return an empty dataframe if no files available, I will push a fix.

**Comment by jnp** [comment]
Created pull request
https://github.com/concurrent-ai/concurrent/pull/29

**Comment by jnp** [comment]
The pull request is merged. This can be resolved as fixed.
